

//added location ,category
export const Posts = [
{
  id: 1,
  type: "job",
  category: "Technology",
  location: "San Francisco, CA",
  employer_id: 1,  // TechNova Co.
  employment_type: "Full-time",
  is_ban: false,
  post_status: "open",
  title: "Frontend Developer",
  post_description: "Build UI with React",
  responsibility: "Develop components",
  work_place_type: "hybrid",
  closed_date: "2026-06-01",
  created_at: "2026-05-01",
  duration: null,
  duration_detail: null,
  schedule: "weekdays",
  hours_per_week: 40,
  benefit: "training",
  language: "English",
  min_salary: 800,
  max_salary: 1200,
  job_role: "Developer",
  job_education: "Bachelor",
  job_experience: "2 years"
},
{
  id: 2,
  type: "job",
  category: "Technology",
  location: "New York, NY",
  employer_id: 1,  // TechNova Co.
  employment_type: "Full-time",
  is_ban: false,
  post_status: "open",
  title: "Backend Developer",
  post_description: "We are looking for an experienced Backend Developer to join our growing team. You will design and build scalable REST APIs that power our applications, working with modern technologies and best practices. The ideal candidate should have strong problem-solving skills and experience with microservices architecture.",
  responsibility: "This fills in the missing description while maintaining consistency with the other post descriptions in your data.",
  work_place_type: "remote",
  closed_date: "2026-06-10",
  created_at: "2026-05-02",
  duration: null,
  duration_detail: null,
  schedule: "weekdays",
  hours_per_week: 40,
  benefit: "certificate",
  language: "English",
  min_salary: 900,
  max_salary: 1500,
  job_role: "Backend",
  job_education: "Bachelor",
  job_experience: "3 years"
},
{
  id: 3,
  type: "job",
  category: "Design",
  location: "Los Angeles, CA",
  employer_id: 12,  // BuildSmart
  employment_type: "Contract",
  is_ban: false,
  post_status: "open",
  title: "UI Designer",
  post_description: "Design UI/UX",
  responsibility: "Create wireframes",
  work_place_type: "onsite",
  closed_date: "2026-06-15",
  created_at: "2026-05-03",
  duration: null,
  duration_detail: null,
  schedule: "weekdays",
  hours_per_week: 40,
  benefit: "training",
  language: "English",
  min_salary: 700,
  max_salary: 1100,
  job_role: "Designer",
  job_education: "Bachelor",
  job_experience: "2 years"
},
{
  id: 4,
  type: "job",
  category: "Technology",
  location: "Austin, TX",
  employer_id: 1,  // TechNova Co.
  employment_type: "Full-time",
  is_ban: false,
  post_status: "open",
  title: "QA Engineer",
  post_description: "Test applications",
  responsibility: "Write test cases",
  work_place_type: "hybrid",
  closed_date: "2026-06-20",
  created_at: "2026-05-04",
  duration: null,
  duration_detail: null,
  schedule: "weekdays",
  hours_per_week: 40,
  benefit: "certificate",
  language: "English",
  min_salary: 600,
  max_salary: 1000,
  job_role: "QA",
  job_education: "Bachelor",
  job_experience: "1 year"
},
{
  id: 5,
  type: "job",
  category: "Business",
  location: "Chicago, IL",
  employer_id: 10,  // MediaWave
  employment_type: "Full-time",
  is_ban: false,
  post_status: "open",
  title: "Project Manager",
  post_description: "Manage projects",
  responsibility: "Lead team",
  work_place_type: "onsite",
  closed_date: "2026-06-25",
  created_at: "2026-05-05",
  duration: null,
  duration_detail: null,
  schedule: "weekdays",
  hours_per_week: 40,
  benefit: "training",
  language: "English",
  min_salary: 1200,
  max_salary: 2000,
  job_role: "Manager",
  job_education: "Bachelor",
  job_experience: "5 years"
},
{
  id: 6,
  type: "job",
  category: "Finance",
  location: "Boston, MA",
  employer_id: 7,  // FinCore
  employment_type: "Part-time",
  is_ban: false,
  post_status: "open",
  title: "Data Analyst",
  post_description: "Analyze data",
  responsibility: "Create reports",
  work_place_type: "remote",
  closed_date: "2026-06-18",
  created_at: "2026-05-06",
  duration: null,
  duration_detail: null,
  schedule: "weekdays",
  hours_per_week: 40,
  benefit: "certificate",
  language: "English",
  min_salary: 700,
  max_salary: 1200,
  job_role: "Analyst",
  job_education: "Bachelor",
  job_experience: "2 years"
},
{
  id: 7,
  type: "job",
  category: "Technology",
  location: "Seattle, WA",
  employer_id: 1,  // TechNova Co.
  employment_type: "Full-time",
  is_ban: false,
  post_status: "open",
  title: "Mobile Developer",
  post_description: "Build mobile apps",
  responsibility: "Develop apps",
  work_place_type: "hybrid",
  closed_date: "2026-06-30",
  created_at: "2026-05-07",
  duration: null,
  duration_detail: null,
  schedule: "weekdays",
  hours_per_week: 40,
  benefit: "training",
  language: "English",
  min_salary: 800,
  max_salary: 1300,
  job_role: "Mobile",
  job_education: "Bachelor",
  job_experience: "2 years"
},
{
  id: 8,
  type: "job",
  category: "Technology",
  location: "Denver, CO",
  employer_id: 1,  // TechNova Co.
  employment_type: "Full-time",
  is_ban: false,
  post_status: "open",
  title: "DevOps Engineer",
  post_description: "Manage CI/CD",
  responsibility: "Deploy systems",
  work_place_type: "remote",
  closed_date: "2026-06-12",
  created_at: "2026-05-08",
  duration: null,
  duration_detail: null,
  schedule: "weekdays",
  hours_per_week: 40,
  benefit: "certificate",
  language: "English",
  min_salary: 1000,
  max_salary: 1600,
  job_role: "DevOps",
  job_education: "Bachelor",
  job_experience: "3 years"
},
{
  id: 9,
  type: "job",
  category: "Technology",
  location: "Portland, OR",
  employer_id: 1,
  employment_type: "Internship",
  is_ban: false,
  post_status: "open",
  title: "System Admin",
  post_description: "Maintain servers",
  responsibility: "Monitor systems",
  work_place_type: "onsite",
  closed_date: "2026-06-22",
  created_at: "2026-05-09",
  duration: null,
  duration_detail: null,
  schedule: "weekdays",
  hours_per_week: 40,
  benefit: "training",
  language: "English",
  min_salary: 700,
  max_salary: 1100,
  job_role: "Admin",
  job_education: "Bachelor",
  job_experience: "2 years"
},
{
  id: 10,
  type: "job",
  category: "Marketing",
  location: "Miami, FL",
  employer_id: 10,  // MediaWave
  employment_type: "Full-time",
  is_ban: false,
  post_status: "open",
  title: "Marketing Specialist",
  post_description: "Handle campaigns",
  responsibility: "Manage ads",
  work_place_type: "hybrid",
  closed_date: "2026-06-28",
  created_at: "2026-05-10",
  duration: null,
  duration_detail: null,
  schedule: "weekdays",
  hours_per_week: 40,
  benefit: "training",
  language: "English",
  min_salary: 600,
  max_salary: 1000,
  job_role: "Marketing",
  job_education: "Bachelor",
  job_experience: "2 years"
},
{
  id: 11,
  type: "volunteer",
  category: "Environment",
  location: "Phnom Penh, Cambodia",
  employer_id: 2,
  is_ban: false,
  post_status: "open",
  title: "Tree Planting Volunteer",
  post_description: "Help plant trees",
  responsibility: "Plant and water trees",
  work_place_type: "onsite",
  closed_date: "2026-05-20",
  created_at: "2026-05-01",
  duration: "one_time",
  duration_detail: "1 day event",
  schedule: "weekend",
  hours_per_week: 5,
  benefit: "certificate",
  language: "Khmer",
  min_salary: null,
  max_salary: null,
  job_role: null,
  job_education: null,
  job_experience: null
},
{
  id: 12,
  type: "volunteer",
  category: "Education",
  location: "Bangkok, Thailand",
  employer_id: 3,
  is_ban: false,
  post_status: "open",
  title: "Teaching Assistant",
  post_description: "Help teach kids",
  responsibility: "Assist teacher",
  work_place_type: "onsite",
  closed_date: "2026-06-01",
  created_at: "2026-05-02",
  duration: "long_term",
  duration_detail: "3 months",
  schedule: "weekdays",
  hours_per_week: 10,
  benefit: "training",
  language: "English",
  min_salary: null,
  max_salary: null,
  job_role: null,
  job_education: null,
  job_experience: null
},
{
  id: 13,
  type: "volunteer",
  category: "Events",
  location: "Ho Chi Minh City, Vietnam",
  employer_id: 13,
  is_ban: false,
  post_status: "open",
  title: "Event Volunteer",
  post_description: "Assist event",
  responsibility: "Help organize",
  work_place_type: "hybrid",
  closed_date: "2026-05-25",
  created_at: "2026-05-03",
  duration: "short_term",
  duration_detail: "2 weeks",
  schedule: "flexible",
  hours_per_week: 8,
  benefit: "certificate",
  language: "English",
  min_salary: null,
  max_salary: null,
  job_role: null,
  job_education: null,
  job_experience: null
}
];

   export const Organizations = [
{
  id: 1,
  name: "TechNova Co.",
  image: "logo1.png",
  about_us: "Software development company",
  organization_type: "Private",
  industry_type: "Technology",
  team_size: "50-100",
  year_establishment: 2018,
  company_vision: "Innovate digital solutions",
  company_email: "contact@technova.com",
  is_ban: false,
  Category: "web_url",
  lable: "Website",
  value: "https://technova.com"
},
{
  id: 2,
  name: "Green Earth NGO",
  image: "logo2.png",
  about_us: "Environmental protection",
  organization_type: "NGO",
  industry_type: "Environment",
  team_size: "20-50",
  year_establishment: 2015,
  company_vision: "Sustainable future",
  company_email: "info@greenearth.org",
  is_ban: false,
  Category: "social",
  lable: "Facebook",
  value: "facebook.com/greenearth"
},
{
  id: 3,
  name: "EduSmart",
  image: "logo3.png",
  about_us: "Online education platform",
  organization_type: "Startup",
  industry_type: "Education",
  team_size: "10-20",
  year_establishment: 2020,
  company_vision: "Accessible learning",
  company_email: "hello@edusmart.com",
  is_ban: false,
  Category: "phone",
  lable: "Hotline",
  value: "+85512345678"
},
{
  id: 4,
  name: "HealthPlus",
  image: "logo4.png",
  about_us: "Healthcare services",
  organization_type: "Private",
  industry_type: "Healthcare",
  team_size: "100-200",
  year_establishment: 2010,
  company_vision: "Better health for all",
  company_email: "support@healthplus.com",
  is_ban: false,
  Category: "web_url",
  lable: "Website",
  value: "https://healthplus.com"
},
{
  id: 5,
  name: "AgriGrow",
  image: "logo5.png",
  about_us: "Agriculture solutions",
  organization_type: "Private",
  industry_type: "Agriculture",
  team_size: "30-60",
  year_establishment: 2016,
  company_vision: "Modern farming",
  company_email: "contact@agrigrow.com",
  is_ban: false,
  Category: "phone",
  lable: "Support",
  value: "+85598765432"
},
{
  id: 6,
  name: "CityBuild",
  image: "logo6.png",
  about_us: "Construction company",
  organization_type: "Private",
  industry_type: "Construction",
  team_size: "200-500",
  year_establishment: 2005,
  company_vision: "Build better cities",
  company_email: "info@citybuild.com",
  is_ban: false,
  Category: "web_url",
  lable: "Website",
  value: "https://citybuild.com"
},
{
  id: 7,
  name: "FinCore",
  image: "logo7.png",
  about_us: "Financial services",
  organization_type: "Corporate",
  industry_type: "Finance",
  team_size: "100-150",
  year_establishment: 2012,
  company_vision: "Empower finance",
  company_email: "contact@fincore.com",
  is_ban: false,
  Category: "social",
  lable: "LinkedIn",
  value: "linkedin.com/fincore"
},
{
  id: 8,
  name: "TravelX",
  image: "logo8.png",
  about_us: "Travel agency",
  organization_type: "Private",
  industry_type: "Tourism",
  team_size: "20-40",
  year_establishment: 2017,
  company_vision: "Explore the world",
  company_email: "support@travelx.com",
  is_ban: false,
  Category: "web_url",
  lable: "Website",
  value: "https://travelx.com"
},
{
  id: 9,
  name: "Foodies Hub",
  image: "logo9.png",
  about_us: "Food delivery service",
  organization_type: "Startup",
  industry_type: "Food",
  team_size: "50-80",
  year_establishment: 2019,
  company_vision: "Delicious everywhere",
  company_email: "info@foodieshub.com",
  is_ban: false,
  Category: "phone",
  lable: "Customer Service",
  value: "+85511223344"
},
{
  id: 10,
  name: "MediaWave",
  image: "logo10.png",
  about_us: "Digital marketing",
  organization_type: "Agency",
  industry_type: "Marketing",
  team_size: "30-70",
  year_establishment: 2014,
  company_vision: "Creative impact",
  company_email: "hello@mediawave.com",
  is_ban: false,
  Category: "social",
  lable: "Instagram",
  value: "instagram.com/mediawave"
},
{
  id: 11,
  name: "AutoDrive",
  image: "logo11.png",
  about_us: "Automobile services",
  organization_type: "Private",
  industry_type: "Automotive",
  team_size: "40-90",
  year_establishment: 2013,
  company_vision: "Drive innovation",
  company_email: "contact@autodrive.com",
  is_ban: false,
  Category: "web_url",
  lable: "Website",
  value: "https://autodrive.com"
},
{
  id: 12,
  name: "BuildSmart",
  image: "logo12.png",
  about_us: "Smart construction tech",
  organization_type: "Startup",
  industry_type: "Technology",
  team_size: "15-30",
  year_establishment: 2021,
  company_vision: "Smart buildings",
  company_email: "info@buildsmart.com",
  is_ban: false,
  Category: "social",
  lable: "Facebook",
  value: "facebook.com/buildsmart"
},
{
  id: 13,
  name: "Care4All",
  image: "logo13.png",
  about_us: "Community support NGO",
  organization_type: "NGO",
  industry_type: "Social",
  team_size: "25-60",
  year_establishment: 2011,
  company_vision: "Help communities",
  company_email: "help@care4all.org",
  is_ban: false,
  Category: "phone",
  lable: "Hotline",
  value: "+85555667788"
},
{
  id: 14,
  name: "SkyNet IT",
  image: "logo14.png",
  about_us: "IT infrastructure",
  organization_type: "Corporate",
  industry_type: "Technology",
  team_size: "80-120",
  year_establishment: 2009,
  company_vision: "Connect the future",
  company_email: "support@skynet.com",
  is_ban: false,
  Category: "web_url",
  lable: "Website",
  value: "https://skynet.com"
},
{
  id: 15,
  name: "EcoLife",
  image: "logo15.png",
  about_us: "Eco-friendly products",
  organization_type: "Startup",
  industry_type: "Retail",
  team_size: "10-25",
  year_establishment: 2022,
  company_vision: "Green living",
  company_email: "hello@ecolife.com",
  is_ban: false,
  Category: "social",
  lable: "Instagram",
  value: "instagram.com/ecolife"
}
];
// Computed summary counts from actual data sources
export const summaryHeroBanners = [
        { id: 1, label: 'Live Job', count: Posts.filter(post => post.type === 'job').length },      
        {id: 2, label:'Live Volunteer', count:Posts.filter(post => post.type==='volunteer').length},
        { id: 3, label: 'Companies', count: Organizations.length },
        { id: 4, label: 'Candidates', count: 5243 }, // Static for now
    ];
    export const summaryPostion = [
        ...new Set(Posts.map(post => post.category))
    ].flatMap((category, index) => [
        {
            id: index * 2 + 1,
            label: category,
            type: 'job',
            count: Posts.filter(post => post.category === category && post.type === 'job').length
        },
        {
            id: index * 2 + 2,
            label: category,
            type: 'volunteer',
            count: Posts.filter(post => post.category === category && post.type === 'volunteer').length
        }
    ])
    export const getOrganizationById = (employerId: number) => {
  return Organizations.find(org => org.id === employerId);
};
export const formatSalary = (post: any) => {
  if (post.type === 'job') {
    return `$${post.min_salary}-$${post.max_salary}`;
  } else {
    return post.benefit || 'Unpaid';
  }
};